export const countries = [
    { name: "Uzbekistan", code: "+998", flag: "🇺🇿", iso: "uz" },
    { name: "Russia", code: "+7", flag: "🇷🇺", iso: "ru" },
    { name: "USA", code: "+1", flag: "🇺🇸", iso: "us" },
    { name: "UK", code: "+44", flag: "🇬🇧", iso: "gb" },
    { name: "Kazakhstan", code: "+7", flag: "🇰🇿", iso: "kz" },
    { name: "Kyrgyzstan", code: "+996", flag: "🇰🇬", iso: "kg" },
    { name: "Tajikistan", code: "+992", flag: "🇹🇯", iso: "tj" },
    { name: "Turkey", code: "+90", flag: "🇹🇷", iso: "tr" },
    { name: "UAE", code: "+971", flag: "🇦🇪", iso: "ae" },
    { name: "Germany", code: "+49", flag: "🇩🇪", iso: "de" },
    { name: "France", code: "+33", flag: "🇫🇷", iso: "fr" },
    { name: "Italy", code: "+39", flag: "🇮🇹", iso: "it" },
    { name: "China", code: "+86", flag: "🇨🇳", iso: "cn" },
    { name: "India", code: "+91", flag: "🇮🇳", iso: "in" },
    { name: "Japan", code: "+81", flag: "🇯🇵", iso: "jp" },
    { name: "South Korea", code: "+82", flag: "🇰🇷", iso: "kr" },
    { name: "Poland", code: "+48", flag: "🇵🇱", iso: "pl" },
    { name: "Spain", code: "+34", flag: "🇪🇸", iso: "es" },
    { name: "Canada", code: "+1", flag: "🇨🇦", iso: "ca" },
    { name: "Brazil", code: "+55", flag: "🇧🇷", iso: "br" },
    { name: "Egypt", code: "+20", flag: "🇪🇬", iso: "eg" },
    { name: "Saudi Arabia", code: "+966", flag: "🇸🇦", iso: "sa" },
    { name: "Ukraine", code: "+380", flag: "🇺🇦", iso: "ua" },
    { name: "Belarus", code: "+375", flag: "🇧🇾", iso: "by" },
    { name: "India", code: "+91", flag: "🇮🇳", iso: "in" },
    { name: "Pakistan", code: "+92", flag: "🇵🇰", iso: "pk" },
    { name: "Azerbaijan", code: "+994", flag: "🇦🇿", iso: "az" },
    { name: "Armenia", code: "+374", flag: "🇦🇲", iso: "am" },
    { name: "Georgia", code: "+995", flag: "🇬🇪", iso: "ge" },
    { name: "Moldova", code: "+373", flag: "🇲🇩", iso: "md" },
    { name: "Israel", code: "+972", flag: "🇮🇱", iso: "il" },
    { name: "Switzerland", code: "+41", flag: "🇨🇭", iso: "ch" },
    { name: "Austria", code: "+43", flag: "🇦🇹", iso: "at" },
    { name: "Netherlands", code: "+31", flag: "🇳🇱", iso: "nl" },
    { name: "Belgium", code: "+32", flag: "🇧🇪", iso: "be" },
    { name: "Sweden", code: "+46", flag: "🇸🇪", iso: "se" },
    { name: "Norway", code: "+47", flag: "🇳🇴", iso: "no" },
    { name: "Denmark", code: "+45", flag: "🇩🇰", iso: "dk" },
    { name: "Finland", code: "+358", flag: "🇫🇮", iso: "fi" },
    { name: "Portugal", code: "+351", flag: "🇵🇹", iso: "pt" },
    { name: "Czech Republic", code: "+420", flag: "🇨🇿", iso: "cz" },
    { name: "Hungary", code: "+36", flag: "🇭🇺", iso: "hu" },
    { name: "Romania", code: "+40", flag: "🇷🇴", iso: "ro" },
    { name: "Bulgaria", code: "+359", flag: "🇧🇬", iso: "bg" },
    { name: "Greece", code: "+30", flag: "🇬🇷", iso: "gr" },
    { name: "Australia", code: "+61", flag: "🇦🇺", iso: "au" },
    { name: "New Zealand", code: "+64", flag: "🇳🇿", iso: "nz" },
    { name: "Canada", code: "+1", flag: "🇨🇦", iso: "ca" },
    { name: "Mexico", code: "+52", flag: "🇲🇽", iso: "mx" },
    { name: "Argentina", code: "+54", flag: "🇦🇷", iso: "ar" },
    { name: "Chile", code: "+56", flag: "🇨🇱", iso: "cl" },
    { name: "Colombia", code: "+57", flag: "🇨🇴", iso: "co" },
    { name: "Malaysia", code: "+60", flag: "🇲🇾", iso: "my" },
    { name: "Singapore", code: "+65", flag: "🇸🇬", iso: "sg" },
    { name: "Thailand", code: "+66", flag: "🇹🇭", iso: "th" },
    { name: "Indonesia", code: "+62", flag: "🇮🇩", iso: "id" },
    { name: "Vietnam", code: "+84", flag: "🇻🇳", iso: "vn" },
    { name: "Philippines", code: "+63", flag: "🇵🇭", iso: "ph" },
];
